#!/usr/bin/env python3
"""
Restore image analysis data from a CMS database export into post_media rows
and .analysis.json files alongside downloaded images.

Usage:
    python telegram/restore_analysis.py --publication dutchrojas
    python telegram/restore_analysis.py --publication dutchrojas --dry-run
    python telegram/restore_analysis.py --publication dutchrojas --database cms_target

Expects the export file at:
    posts/saved/images/{publication}/_analysis_export.json

Generated by exporting from the CMS database (see conversation history).
"""

import argparse
import json
import sys
from pathlib import Path

import psycopg2

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from db.config import get_db_config


def load_export(publication):
    export_path = Path(f"posts/saved/images/{publication}/_analysis_export.json")
    if not export_path.exists():
        print(f"ERROR: Export file not found: {export_path}", file=sys.stderr)
        sys.exit(1)
    with open(export_path) as f:
        return json.load(f)


def find_local_image(post_id, source_url, publication):
    """Find the downloaded image file matching a source URL."""
    # Images are in posts/saved/images/{pub}/{post_id}/ or posts/saved/covers/{pub}/{post_id}/
    for base in ["posts/saved/images", "posts/saved/covers"]:
        img_dir = Path(base) / publication / str(post_id)
        if not img_dir.exists():
            continue
        # Match by filename from URL (last path component, minus query params)
        url_filename = source_url.rstrip('/').split('/')[-1].split('?')[0]
        for f in img_dir.iterdir():
            if f.name == url_filename:
                return f
            # Also try matching by the image hash portion (UUID pattern in substack URLs)
            if url_filename in f.name or f.stem in source_url:
                return f
    return None


def main():
    parser = argparse.ArgumentParser(description='Restore image analysis from CMS export')
    parser.add_argument('--publication', '-p', required=True, help='Publication subdomain')
    parser.add_argument('--database', default='substack', help='Target PostgreSQL database (default: substack)')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be done without writing')
    args = parser.parse_args()

    records = load_export(args.publication)
    print(f"Loaded {len(records)} analysis records from export")

    config = get_db_config()
    config['database'] = args.database
    conn = psycopg2.connect(**config)
    cur = conn.cursor()

    matched_files = 0
    matched_db = 0
    skipped_no_file = 0
    skipped_no_media = 0

    for r in records:
        post_id = r["post_id"]
        image_url = r["image_url"]
        analysis = r["analysis"]
        model = r.get("analysis_model", "cms-export")

        # 1. Write .analysis.json alongside the image file
        local_path = find_local_image(post_id, image_url, args.publication)
        if local_path:
            json_path = local_path.with_suffix(local_path.suffix + ".analysis.json")
            if args.dry_run:
                print(f"  WRITE {json_path}")
            else:
                json_path.write_text(json.dumps(analysis, indent=2, ensure_ascii=False))
            matched_files += 1
        else:
            skipped_no_file += 1

        # 2. Update post_media row in the target database
        # Match by post_id and source_url containing the same image path
        # Extract the UUID filename from the URL for flexible matching
        # URLs may be URL-encoded CDN paths; decode and grab the filename
        from urllib.parse import unquote
        decoded_url = unquote(image_url)
        s3_key = decoded_url.rstrip('/').split('/')[-1].split('?')[0]

        cur.execute("""
            SELECT media_id, local_path FROM substack.post_media
            WHERE post_id = %s AND source_url LIKE %s
            LIMIT 1
        """, (post_id, f'%{s3_key}%'))
        row = cur.fetchone()

        if row:
            media_id = row[0]
            if args.dry_run:
                print(f"  UPDATE media_id={media_id} post={post_id}")
            else:
                cur.execute("""
                    UPDATE substack.post_media
                    SET image_description = %s,
                        image_data = %s,
                        image_category = %s,
                        analysis_model = %s,
                        analyzed_at = NOW(),
                        analysis_error = NULL
                    WHERE media_id = %s
                """, (
                    analysis.get("description"),
                    json.dumps(analysis.get("data")) if analysis.get("data") else None,
                    analysis.get("category"),
                    model,
                    media_id,
                ))
            matched_db += 1

            # Also write .analysis.json using local_path from DB if we didn't find it above
            if not local_path and row[1]:
                db_local = Path(row[1])
                if db_local.exists():
                    json_path = db_local.with_suffix(db_local.suffix + ".analysis.json")
                    if not args.dry_run:
                        json_path.write_text(json.dumps(analysis, indent=2, ensure_ascii=False))
                    matched_files += 1
                    skipped_no_file -= 1
        else:
            skipped_no_media += 1

    if not args.dry_run:
        conn.commit()

    conn.close()

    print(f"\nResults:")
    print(f"  Analysis JSON files written: {matched_files}")
    print(f"  Database rows updated:       {matched_db}")
    print(f"  No image file on disk:       {skipped_no_file}")
    print(f"  No post_media row found:     {skipped_no_media}")


if __name__ == '__main__':
    main()
